import { Router } from 'express';
import { adminRouter } from './admin.routes.js';
import { adsRouter } from './ads.routes.js';
import { authRouter } from './auth.routes.js';
import { blogsRouter } from './blogs.routes.js';
import { chatRouter } from './chat.routes.js';
import { earningsRouter } from './earnings.routes.js';
import { feedbackRouter } from './feedback.routes.js';
import { healthRouter } from './health.routes.js';
import { musicRouter } from './music.routes.js';
import { notificationsRouter } from './notifications.routes.js';
import { postsRouter } from './posts.routes.js';
import { soundsRouter } from './sounds.routes.js';
import { storiesRouter } from './stories.routes.js';
import { uploadsRouter } from './uploads.routes.js';
import { usersRouter } from './users.routes.js';
import { withdrawalsRouter } from './withdrawals.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/uploads', uploadsRouter);
apiRouter.use('/posts', postsRouter);
apiRouter.use('/sounds', soundsRouter);
apiRouter.use('/stories', storiesRouter);
apiRouter.use('/blogs', blogsRouter);
apiRouter.use('/chat', chatRouter);
apiRouter.use('/earnings', earningsRouter);
apiRouter.use('/feedback', feedbackRouter);
apiRouter.use('/music', musicRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/withdrawals', withdrawalsRouter);
apiRouter.use('/ads', adsRouter);
apiRouter.use('/admin', adminRouter);
